"""initial schema — users, projects, tasks, team_members

Revision ID: 9efc4f1a0f5a
Revises: 
Create Date: 2026-07-30 17:24:01.978300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efc4f1a0f5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_code', sa.String(length=20), nullable=False),
    sa.Column('engagement_type', sa.String(length=50), nullable=False),
    sa.Column('client_alias', sa.String(length=200), nullable=False),
    sa.Column('project_name', sa.String(length=300), nullable=False),
    sa.Column('project_type_api', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('health', sa.String(length=50), nullable=False),
    sa.Column('owner_alias', sa.String(length=200), nullable=False),
    sa.Column('owner_role', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('business_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('open_tasks', sa.Integer(), nullable=False),
    sa.Column('overdue_tasks', sa.Integer(), nullable=False),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recent_completed_examples', sa.Text(), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_alias', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('projects_in_portfolio', sa.Integer(), nullable=False),
    sa.Column('open_tasks_assigned', sa.Integer(), nullable=False),
    sa.Column('blocked_tasks_assigned', sa.Integer(), nullable=False),
    sa.Column('high_or_critical_open', sa.Integer(), nullable=False),
    sa.Column('diagnostico_projects', sa.Integer(), nullable=False),
    sa.Column('proyecto_projects', sa.Integer(), nullable=False),
    sa.Column('mantenimiento_projects', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_member_alias'), 'team_members', ['member_alias'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_code', sa.String(length=30), nullable=False),
    sa.Column('project_code', sa.String(length=20), nullable=False),
    sa.Column('assignee_alias', sa.String(length=200), nullable=False),
    sa.Column('assignee_role', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('dependency', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('last_progress', sa.Text(), nullable=True),
    sa.Column('engagement_type', sa.String(length=50), nullable=True),
    sa.Column('client_alias', sa.String(length=200), nullable=True),
    sa.Column('project_name', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_project_code'), 'tasks', ['project_code'], unique=False)
    op.create_index(op.f('ix_tasks_task_code'), 'tasks', ['task_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_task_code'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_code'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_team_members_member_alias'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
