"""add_risk_metrics

Revision ID: e8b672a375f5
Revises: 9efc4f1a0f5a
Create Date: 2026-07-30 20:00:35.735060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b672a375f5'
down_revision: Union[str, Sequence[str], None] = '9efc4f1a0f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('risk_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('projects', sa.Column('risk_level', sa.String(length=50), server_default='Low', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'risk_level')
    op.drop_column('projects', 'risk_score')
    # ### end Alembic commands ###
